from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from .views import *
# from rest_framework import routers
from rest_framework_mongoengine import routers
from rest_framework_mongoengine import generics as drfme_generics

# this is DRF router for REST API viewsets
# router = routers.DefaultRouter()
router = routers.DefaultRouter(trailing_slash=False)

# register REST API endpoints with DRF router
router.register(r'tools', ToolViewSet, 'tools')
router.register(r'users', UserList, 'users')
router.register(r'blogs', BlogList, 'blogs')
router.register(r'posts', PostList, 'posts')
router.register(r'comments', CommentList, 'comments')
router.register(r'^snippets', SnippetList, 'SnippetList')
# router.register(r'tools/(?P<pk>[0-9]+)/$', ToolViewSet, 'tool_pk')
# router.register(r'users', User_view_set, 'user')
# router.register(r'users/(?P<pk>[0-9]+)/$', User_view_set, 'user_pk')
# router.register(r'^snippets/(?P<pk>[0-9]+)/$', SnippetDetail, "SnippetDetail")
# router.register(r'^messages', MessageList, 'MessageList')
urlpatterns = [
    # default django admin interface
    url(r'^admin/', include(admin.site.urls)),

    # REST API root view (generated by DRF router)
    url(r'^api/', include(router.urls, namespace='api')),

    # pure django views that don't use DRF
    url(r'^$', homepage, {}, name='index'),

    # added the below lines of code
    # url(r'^snippets/$', SnippetList.as_view()),
    # url(r'^snippets/(?P<pk>[0-9]+)/$', SnippetDetail.as_view()),

]

# in development django built-in server serves static and media content
# if not settings.PRODUCTION:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)